#ifndef FRAMEBUFFERWC_CONTROL_H
#define FRAMEBUFFERWC_CONTROL_H

#define FRAMEBUFFERWC_CONTROL_PARAMETER "FramebufferWCControl"
#define FRAMEBUFFERWC_STATUS_PARAMETER "FramebufferWCStatus"
#define FRAMEBUFFERWC_VERSION_PARAMETER "FramebufferWCDriverVersion"

#define FRAMEBUFFERWC_STATUS_SCHEMA_VERSION 1U

typedef enum FramebufferWCStatusIndex {
    FRAMEBUFFERWC_STATUS_SCHEMA = 0,
    FRAMEBUFFERWC_STATUS_READY,
    FRAMEBUFFERWC_STATUS_STATE,
    FRAMEBUFFERWC_STATUS_WRITE_COUNT,
    FRAMEBUFFERWC_STATUS_COUNT
} FramebufferWCStatusIndex;

typedef enum FramebufferWCState {
    FRAMEBUFFERWC_STATE_UNAVAILABLE = 0,
    FRAMEBUFFERWC_STATE_OFF = 1,
    FRAMEBUFFERWC_STATE_ON = 2,
    FRAMEBUFFERWC_STATE_INCONSISTENT = 3
} FramebufferWCState;

#endif
