MAKEFILEDIR = /NextDeveloper/Makefiles/driverkit
MAKEFILE = Makefile.main_driver
PRIVATE_DEFINES = -DKERNEL_PRIVATE -DDRIVER_PRIVATE
OTHER_CFLAGS = -Wall -no-precomp \
	-I/LocalDeveloper/Headers $(PRIVATE_DEFINES)
